# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mapElevMaker
                                 A QGIS plugin
 Create contours and shadings for hiking maps - to be used with QuickOSM presets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-05
        copyright            : (C) 2025 by Alberto Bianco
        email                : albbianc@proton.me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mapElevMaker class from file mapElevMaker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_elev_maker import mapElevMaker
    return mapElevMaker(iface)
